### ISSUE TITLE
Compiler Errors main.cpp:32

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#1]
Hi, I really want to use ESP32 to read the data from AlphaInnotec and push it via MQTT to homeassistant.
This error is shown, when I compile the yaml:
`In file included from src/main.cpp:32:
src/luxtronik_v1_sensor.h:18:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_VL           = new Sensor();  // Temperatur Vorlauf  -> 1100/2
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:19:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_RL           = new Sensor();  // Temperatur Rücklauf -> 1100/3
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:20:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_RL_Soll      = new Sensor();  // Temperatur Rücklauf-Soll -> 1100/4
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:21:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_Heissgas     = new Sensor();  // 1100/5
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:22:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_Aussen       = new Sensor();  // 1100/6
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:23:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_BW           = new Sensor();  // 1100/7
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:24:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_BW_Soll      = new Sensor();  // 1100/8
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:25:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_WQ_Ein       = new Sensor();  // 1100/9
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:26:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_Kaeltekreis  = new Sensor();  // 1100/10
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:27:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_MK1_Vorl     = new Sensor();  // 1100/11
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:28:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_MK1VL_Soll   = new Sensor();  // 1100/12
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:29:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *temp_Raumstat     = new Sensor();  // 1100/13
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:31:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *ein_Abtau_Soledruck_Durchfluss  = new Sensor();  // 1200/2
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:32:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *ein_Sperrzeit_EVU               = new Sensor();  // 1200/3
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:33:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *ein_Hochdruckpressostat         = new Sensor();  // 1200/4
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:34:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *ein_Motorschutz                 = new Sensor();  // 1200/5
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:35:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *ein_Niederdruckpressostat       = new Sensor();  // 1200/6
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:36:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *ein_Fremdstromanode             = new Sensor();  // 1200/7
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:38:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_ATV             = new Sensor();  // 1300/2
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:39:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_BWP             = new Sensor();  // 1300/3
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:40:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_FBHP            = new Sensor();  // 1300/4
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:41:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_HZP             = new Sensor();  // 1300/5
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:42:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_Mischer_1_Auf   = new Sensor();  // 1300/6
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:43:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_Mischer_1_Zu    = new Sensor();  // 1300/7
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:44:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_VentWP          = new Sensor();  // 1300/8
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:45:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_VentBrunnen     = new Sensor();  // 1300/9
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:46:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_Verdichter_1    = new Sensor();  // 1300/10
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:47:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_Verdichter_2    = new Sensor();  // 1300/11
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:48:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_ZPumpe          = new Sensor();  // 1300/12
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h:49:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_ZWE             = new Sensor();  // 1300/13
   ^~~~~~
   gens
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\AsyncEventSource.cpp.o
src/luxtronik_v1_sensor.h:50:3: error: 'Sensor' does not name a type; did you mean 'gens'?
   Sensor *aus_ZWE_Stoerung    = new Sensor();  // 1300/14
   ^~~~~~
   gens
src/luxtronik_v1_sensor.h: In member function 'void esphome::luxtronik_v1_sensor::parse_cmd_(std::__cxx11::string)':
src/luxtronik_v1_sensor.h:120:9: error: 'temp_VL' was not declared in this scope
         temp_VL->publish_state(GetFloatTemp(tmp_VL));
         ^~~~~~~
src/luxtronik_v1_sensor.h:120:9: note: suggested alternative: 'tmp_VL'
         temp_VL->publish_state(GetFloatTemp(tmp_VL));
         ^~~~~~~
         tmp_VL
src/luxtronik_v1_sensor.h:126:9: error: 'temp_RL' was not declared in this scope
         temp_RL->publish_state(GetFloatTemp(tmp_RL));
         ^~~~~~~
src/luxtronik_v1_sensor.h:126:9: note: suggested alternative: 'tmp_RL'
         temp_RL->publish_state(GetFloatTemp(tmp_RL));
         ^~~~~~~
         tmp_RL
src/luxtronik_v1_sensor.h:132:9: error: 'temp_RL_Soll' was not declared in this scope
         temp_RL_Soll->publish_state(GetFloatTemp(tmp_RL_Soll));
         ^~~~~~~~~~~~
src/luxtronik_v1_sensor.h:132:9: note: suggested alternative: 'tmp_RL_Soll'
         temp_RL_Soll->publish_state(GetFloatTemp(tmp_RL_Soll));
         ^~~~~~~~~~~~
         tmp_RL_Soll
src/luxtronik_v1_sensor.h:138:9: error: 'temp_Heissgas' was not declared in this scope
         temp_Heissgas->publish_state(GetFloatTemp(tmp_Heissgas));
         ^~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:138:9: note: suggested alternative: 'tmp_Heissgas'
         temp_Heissgas->publish_state(GetFloatTemp(tmp_Heissgas));
         ^~~~~~~~~~~~~
         tmp_Heissgas
src/luxtronik_v1_sensor.h:144:9: error: 'temp_Aussen' was not declared in this scope
         temp_Aussen->publish_state(GetFloatTemp(tmp_Aussen));
         ^~~~~~~~~~~
src/luxtronik_v1_sensor.h:144:9: note: suggested alternative: 'tmp_Aussen'
         temp_Aussen->publish_state(GetFloatTemp(tmp_Aussen));
         ^~~~~~~~~~~
         tmp_Aussen
src/luxtronik_v1_sensor.h:150:9: error: 'temp_BW' was not declared in this scope
         temp_BW->publish_state(GetFloatTemp(tmp_BW));
         ^~~~~~~
src/luxtronik_v1_sensor.h:150:9: note: suggested alternative: 'tmp_BW'
         temp_BW->publish_state(GetFloatTemp(tmp_BW));
         ^~~~~~~
         tmp_BW
src/luxtronik_v1_sensor.h:156:9: error: 'temp_BW_Soll' was not declared in this scope
         temp_BW_Soll->publish_state(GetFloatTemp(tmp_BW_Soll));
         ^~~~~~~~~~~~
src/luxtronik_v1_sensor.h:156:9: note: suggested alternative: 'tmp_BW_Soll'
         temp_BW_Soll->publish_state(GetFloatTemp(tmp_BW_Soll));
         ^~~~~~~~~~~~
         tmp_BW_Soll
src/luxtronik_v1_sensor.h:162:9: error: 'temp_WQ_Ein' was not declared in this scope
         temp_WQ_Ein->publish_state(GetFloatTemp(tmp_WQ_Ein));
         ^~~~~~~~~~~
src/luxtronik_v1_sensor.h:162:9: note: suggested alternative: 'tmp_WQ_Ein'
         temp_WQ_Ein->publish_state(GetFloatTemp(tmp_WQ_Ein));
         ^~~~~~~~~~~
         tmp_WQ_Ein
src/luxtronik_v1_sensor.h:168:9: error: 'temp_Kaeltekreis' was not declared in this scope
         temp_Kaeltekreis->publish_state(GetFloatTemp(tmp_Kaeltekreis));
         ^~~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:168:9: note: suggested alternative: 'tmp_Kaeltekreis'
         temp_Kaeltekreis->publish_state(GetFloatTemp(tmp_Kaeltekreis));
         ^~~~~~~~~~~~~~~~
         tmp_Kaeltekreis
src/luxtronik_v1_sensor.h:174:9: error: 'temp_MK1_Vorl' was not declared in this scope
         temp_MK1_Vorl->publish_state(GetFloatTemp(tmp_MK1_Vorl));
         ^~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:174:9: note: suggested alternative: 'tmp_MK1_Vorl'
         temp_MK1_Vorl->publish_state(GetFloatTemp(tmp_MK1_Vorl));
         ^~~~~~~~~~~~~
         tmp_MK1_Vorl
src/luxtronik_v1_sensor.h:180:9: error: 'temp_MK1VL_Soll' was not declared in this scope
         temp_MK1VL_Soll->publish_state(GetFloatTemp(tmp_MK1VL_Soll));
         ^~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:180:9: note: suggested alternative: 'tmp_MK1VL_Soll'
         temp_MK1VL_Soll->publish_state(GetFloatTemp(tmp_MK1VL_Soll));
         ^~~~~~~~~~~~~~~
         tmp_MK1VL_Soll
src/luxtronik_v1_sensor.h:186:9: error: 'temp_Raumstat' was not declared in this scope
         temp_Raumstat->publish_state(GetFloatTemp(tmp_Raumstat));
         ^~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:186:9: note: suggested alternative: 'tmp_Raumstat'
         temp_Raumstat->publish_state(GetFloatTemp(tmp_Raumstat));
         ^~~~~~~~~~~~~
         tmp_Raumstat
src/luxtronik_v1_sensor.h:203:9: error: 'ein_Abtau_Soledruck_Durchfluss' was not declared in this scope
         ein_Abtau_Soledruck_Durchfluss->publish_state(GetInputOutputState(tmp_in));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Archiving .pioenvs\luxtronik\lib39f\libAsyncTCP-esphome.a
src/luxtronik_v1_sensor.h:208:9: error: 'ein_Sperrzeit_EVU' was not declared in this scope
         ein_Sperrzeit_EVU->publish_state(GetInputOutputState(tmp_in));
         ^~~~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:213:9: error: 'ein_Hochdruckpressostat' was not declared in this scope
         ein_Hochdruckpressostat->publish_state(GetInputOutputState(tmp_in));
         ^~~~~~~~~~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:218:9: error: 'ein_Motorschutz' was not declared in this scope
         ein_Motorschutz->publish_state(GetInputOutputState(tmp_in));
         ^~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:223:9: error: 'ein_Niederdruckpressostat' was not declared in this scope
         ein_Niederdruckpressostat->publish_state(GetInputOutputState(tmp_in));
         ^~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o
src/luxtronik_v1_sensor.h:228:9: error: 'ein_Fremdstromanode' was not declared in this scope
         ein_Fremdstromanode->publish_state(GetInputOutputState(tmp_in));
         ^~~~~~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:245:9: error: 'aus_ATV' was not declared in this scope
         aus_ATV->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~
src/luxtronik_v1_sensor.h:250:9: error: 'aus_BWP' was not declared in this scope
         aus_BWP->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~
src/luxtronik_v1_sensor.h:255:9: error: 'aus_FBHP' was not declared in this scope
         aus_FBHP->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~
src/luxtronik_v1_sensor.h:260:9: error: 'aus_HZP' was not declared in this scope
         aus_HZP->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~
src/luxtronik_v1_sensor.h:265:9: error: 'aus_Mischer_1_Auf' was not declared in this scope
         aus_Mischer_1_Auf->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~~
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\WebAuthentication.cpp.o
src/luxtronik_v1_sensor.h:270:9: error: 'aus_Mischer_1_Zu' was not declared in this scope
         aus_Mischer_1_Zu->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\WebHandlers.cpp.o
src/luxtronik_v1_sensor.h:275:9: error: 'aus_VentWP' was not declared in this scope
         aus_VentWP->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\WebRequest.cpp.o
src/luxtronik_v1_sensor.h:280:9: error: 'aus_VentBrunnen' was not declared in this scope
         aus_VentBrunnen->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\WebResponses.cpp.o
src/luxtronik_v1_sensor.h:285:9: error: 'aus_Verdichter_1' was not declared in this scope
         aus_Verdichter_1->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~
Compiling .pioenvs\luxtronik\libe88\ESPAsyncWebServer-esphome\WebServer.cpp.o
src/luxtronik_v1_sensor.h:285:9: note: suggested alternative: 'u_register_t'
         aus_Verdichter_1->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~
         u_register_t
src/luxtronik_v1_sensor.h:290:9: error: 'aus_Verdichter_2' was not declared in this scope
         aus_Verdichter_2->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~
src/luxtronik_v1_sensor.h:290:9: note: suggested alternative: 'u_register_t'
         aus_Verdichter_2->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~
         u_register_t
src/luxtronik_v1_sensor.h:295:9: error: 'aus_ZPumpe' was not declared in this scope
         aus_ZPumpe->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~
src/luxtronik_v1_sensor.h:300:9: error: 'aus_ZWE' was not declared in this scope
         aus_ZWE->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~
src/luxtronik_v1_sensor.h:305:9: error: 'aus_ZWE_Stoerung' was not declared in this scope
         aus_ZWE_Stoerung->publish_state(GetInputOutputState(tmp_out));
         ^~~~~~~~~~~~~~~~
Compiling .pioenvs\luxtronik\lib72f\DNSServer\DNSServer.cpp.o
Compiling .pioenvs\luxtronik\lib94e\ESPmDNS\ESPmDNS.cpp.o
Compiling .pioenvs\luxtronik\FrameworkArduino\Esp.cpp.o
Compiling .pioenvs\luxtronik\FrameworkArduino\FirmwareMSC.cpp.o
*** [.pioenvs\luxtronik\src\main.cpp.o] Error 1
============================================= [FAILED] Took 146.79 seconds ====`

Kind regards
Axel

**Comment by CBrosius** [comment]
Hi Axel, this is exactly what I am doing. I use a ESP8266 Wemos D1 Mini in my YAML-Code.
Did you change this to your ESP32-Board?

Kind regards,
Christian...

**Comment by optimismus** [comment]
Hi Christian,
I tried to use an nodemcu ESP32. This is, how I edited the yaml file:
`esphome:
  name: luxtronik
  includes:
    - luxtronik_v1_sensor.h

esp32:
  board: nodemcu-32s
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "mywifi"
  password: "wpa-secret"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Luxtronik Fallback Hotspot"
    password: "secret"

captive_portal:

web_server:
  port: 80

mqtt:
  broker: 192.168.1.1
  # Optional variables:
  discovery: true

# Schnittstellen-Parameter: 57600, 8, N, 1
uart:
  baud_rate: 57600
  rx_pin: GPIO3
  tx_pin: GPIO1
  # baud_rate (Required, int): The baud rate of the UART bus.
  # rx_pin (Optional, Pin): The pin to receive data on from the ESP’s perspective.
  # tx_pin (Optional, Pin): The pin to send data to from the ESP’s perspective.
  data_bits: 8
  #data_bits (Optional, int): The number of data bits used on the UART bus. Options: 5 to 8. Defaults to 8.
  #parity (Optional): The parity used on the UART bus. Options: NONE, EVEN, ODD. Defaults to NONE.
  parity: NONE
  #stop_bits (Optional, int): The number of stop bits to send. Options: 1, 2. Defaults to 1.
  stop_bits: 1
  # id (Optional, ID): Manually specify the ID for this UART hub if you need multiple UART hubs
  id: uart_bus
    

    `
But obviously that was wrong.
I put out an d1 mini and used that, it works, no compiler errors.
