### ISSUE TITLE
WP_Temp_Mischkreis_1_Soll_Vorlauftemperatur is 0°C

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#18]
The "Soll_Vorlauftemperatur" is always 0°C.

**Comment by CBrosius** [comment]
Did you recheck that with the values in the heatpump via the Display (Service -> Informations -> Temperaturen -> MK1VL-Soll)
In my Heatpump this value is always 0°C, too. 
<img width="949" alt="image" src="https://github.com/CBrosius/luxtronik_v1/assets/23188584/b0c42e58-fb44-4c50-a2c7-da01e2301196">

**Comment by optimismus** [comment]
Just checked it an you are absolutly right, sorry, didn't expected that. My setting is 0,0°C too.
