### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#2]
Hi Christian,
please add a licence to your repository e.g. via https://choosealicense.com/no-permission/ because I want to contribute to your project.

Regards
Axel

**Comment by CBrosius** [comment]
I added a MIT License File to the repo. Is that sufficient?

**Comment by optimismus** [comment]
Thank you a lot, for your fast reaction!

BTW I tried to contact via homeassistant-community too
