### ISSUE TITLE
Workinprogress branch uses GPIO2 and GPIO4

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#21]
The yaml of the work in progress branch is still on GPIO2 RX und GPIO4 TX (had to change to GPIO16 and GPIO17 because of the cabeling).

**Comment by CBrosius** [comment]
Oh I see. I never changed GPIOs on my production-system, thats where this is coming from.
Maybe I should change this to be on par with the documentation.

**Comment by CBrosius** [comment]
fixed in the WorkInProgress-branch.
