### ISSUE TITLE
esp32 compiling errors 'class esphome::luxtronik_v1_sensor' has no member named 'status_Anlagentyp'

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#3]
I tried to use the esp32-example, but got compiler errors:

Compiling .pioenvs\luxtronik-v1-esp32\liba95\Update\Updater.cpp.o
luxtronik-v1-esp32.yaml: In lambda function:
luxtronik-v1-esp32.yaml:92:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Anlagentyp'
luxtronik-v1-esp32.yaml:93:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Softwareversion'; did you mean 'status_clear_error'?
luxtronik-v1-esp32.yaml:94:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Bivalenzstufe'
luxtronik-v1-esp32.yaml:95:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Betriebszustand'
luxtronik-v1-esp32.yaml:96:7: error: could not convert '{luxtronik_v1->esphome::luxtronik_v1_sensor::temp_VL, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_RL, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_RL_Soll, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Heissgas, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Aussen, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_BW, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_BW_Soll, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_WQ_Ein, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Kaeltekreis, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_MK1_Vorl, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_MK1VL_Soll, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Raumstat, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Abtau_Soledruck_Durchfluss, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Sperrzeit_EVU, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Hochdruckpressostat, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Motorschutz, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Niederdruckpressostat, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Fremdstromanode, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ATV, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_BWP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_FBHP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_HZP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Mischer_1_Auf, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Mischer_1_Zu, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_VentWP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_VentBrunnen, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Verdichter_1, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Verdichter_2, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ZPumpe, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ZWE, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ZWE_Stoerung, <expression error>, <expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\AsyncEventSource.cpp.o
Archiving .pioenvs\luxtronik-v1-esp32\lib21b\libAsyncTCP-esphome.a
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebAuthentication.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebHandlers.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebRequest.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebResponses.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebServer.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\lib94e\ESPmDNS\ESPmDNS.cpp.o
*** [.pioenvs\luxtronik-v1-esp32\src\main.cpp.o] Error 1
============================================= [FAILED] Took 40.26 seconds =

**Comment by CBrosius** [comment]
You are right, I forgot to add the 2 new attributes to the esp32.yaml.
They are included now. Does this fix your compile-errors?

**Comment by optimismus** [comment]
Sorry: No.
I deleted the temporary folder under .eshome/build for esp32, but this ist the result (only the error part):
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\AsyncEventSource.cpp.o
luxtronik-v1-esp32.yaml: In lambda function:
luxtronik-v1-esp32.yaml:92:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Anlagentyp'
luxtronik-v1-esp32.yaml:93:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Softwareversion'; did you mean 'status_clear_error'?
luxtronik-v1-esp32.yaml:94:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Bivalenzstufe'
luxtronik-v1-esp32.yaml:95:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'status_Betriebszustand'
luxtronik-v1-esp32.yaml:96:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'modus_Heizung'
luxtronik-v1-esp32.yaml:97:23: error: 'class esphome::luxtronik_v1_sensor' has no member named 'modus_Warmwasser'
luxtronik-v1-esp32.yaml:98:7: error: could not convert '{luxtronik_v1->esphome::luxtronik_v1_sensor::temp_VL, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_RL, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_RL_Soll, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Heissgas, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Aussen, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_BW, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_BW_Soll, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_WQ_Ein, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Kaeltekreis, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_MK1_Vorl, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_MK1VL_Soll, luxtronik_v1->esphome::luxtronik_v1_sensor::temp_Raumstat, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Abtau_Soledruck_Durchfluss, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Sperrzeit_EVU, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Hochdruckpressostat, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Motorschutz, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Niederdruckpressostat, luxtronik_v1->esphome::luxtronik_v1_sensor::ein_Fremdstromanode, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ATV, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_BWP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_FBHP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_HZP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Mischer_1_Auf, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Mischer_1_Zu, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_VentWP, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_VentBrunnen, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Verdichter_1, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_Verdichter_2, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ZPumpe, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ZWE, luxtronik_v1->esphome::luxtronik_v1_sensor::aus_ZWE_Stoerung, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
Archiving .pioenvs\luxtronik-v1-esp32\lib21b\libAsyncTCP-esphome.a
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebAuthentication.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebHandlers.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebRequest.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebResponses.cpp.o
Compiling .pioenvs\luxtronik-v1-esp32\libc20\ESPAsyncWebServer-esphome\WebServer.cpp.o
*** [.pioenvs\luxtronik-v1-esp32\src\main.cpp.o] Error 1
============================================= [FAILED] Took 33.65 seconds =============================================
Seem to be the same error.

I attach an image of my board, just to be sure it is compatible with your config:
 
![IMG_20230831_210015](https://github.com/CBrosius/luxtronik_v1/assets/16720046/4d1cc84a-fb80-4cd2-91d2-f0cb799734c3)

**Comment by optimismus** [comment]
After deleting all temp dirs and recompiling it compiles successfully. Thanks a lot for your work.
