### ISSUE TITLE
WP_Modus_Warmwasser missing

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#5]
I use the ESP32.yaml.
Although

`22:02:59 | [D] | [luxtronik_v1:417] | 3405 found -> Heizungsmodus
-- | -- | -- | --
22:02:59 | [D] | [luxtronik_v1:418] | R: 3405;1;4 - 0
22:02:59 | [D] | [sensor:094] | 'WP_Status_Betriebszustand': Sending state 4.00000  with 0 decimals of accuracy
22:02:59 | [D] | [luxtronik_v1:115] | S: 3505 - 0
22:02:59 | [D] | [luxtronik_v1:435] | 3505 found -> Warmwassermodus
22:02:59 | [D] | [luxtronik_v1:436] | R: 3505;1;0 - 0
22:02:59 | [D] | [sensor:094] | 'WP_Modus_Heizung': Sending state 0.00000  with 0 decimals of accuracy`

it is not shown and not an entity in Homeassistant.

**Comment by CBrosius** [comment]
Sensor-Entry for WP_Modus_Warmwasser was missing. This is added, now.
