### ISSUE TITLE
Softwareversion "NA"

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#6]
I use the esp32.yaml.
Although in the log the software version is given by the heat pump:
"22:03:58 | [D] | [luxtronik_v1:356] | Softwareversion:  V2.33"

it is not shown in the webinterface nor in the HA entity.
I assume this ist caused by a leading blank sign at the beginning of the string:
"1700;12;11; **V2.33**;1;5;25;8;23;9;49;16,0,0"

**Comment by CBrosius** [comment]
Yes the responding part in [luxtronik_v1_sensor.h](https://github.com/CBrosius/luxtronik_v1/blob/main/luxtronik_v1_sensor.h) (line 356) is not implemented. But I put it back in my todo-list until other things are working. 
All other values are numbers, but the Version is a String. So this has to be implemented different.

**Comment by CBrosius** [comment]
From now on I handle the software-version as a float with two digits.
So this issue should be fixed for now.
