### ISSUE TITLE
Update to ESPHOME 2023.10 broke ESP32

### ISSUE THREAD

**Issue by optimismus** [CBrosius/luxtronik_v1#9]
After updating to ESPHOME 2023.10 inside of HA, the ESP32 stops working. It was still in the network (pingable), but doesn't even expose the webinterface nor connect via ESPHOME.

**Comment by CBrosius** [comment]
I cannot reproduce this issue. Update to 2023.10 and 2023.10.1 went flawless on my side.

**Comment by optimismus** [comment]
I reproduced the issue today: Is your ESP connected to heatpump? (my is)
Before:
![luxtronikv1-01](https://github.com/CBrosius/luxtronik_v1/assets/16720046/ef95efc5-9d28-410b-89c3-74f378f00547)

![luxtronikv1-02](https://github.com/CBrosius/luxtronik_v1/assets/16720046/07b667c4-4436-46bd-aa21-15b46e0d1e10)
after installing 2023.10.1 the luxtronik-v1-esp32.local is available in network:
>Ping wird ausgeführt für luxtronik-v1-esp32.local [192.168.178.51] mit 32 Bytes Daten:
>Antwort von 192.168.178.51: Bytes=32 Zeit=153ms TTL=255
>Antwort von 192.168.178.51: Bytes=32 Zeit=339ms TTL=255

but webserver (http://luxtronik-v1-esp32.local/) nor API calls are working:
>INFO ESPHome 2023.10.1
INFO Reading configuration /config/esphome/luxtronik-v1-esp32.yaml...
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Starting log output from luxtronik-v1-esp32.local using esphome API
WARNING Can't connect to ESPHome API for luxtronik-v1-esp32.local: Error connecting to ('192.168.178.51', 6053): [Errno 111] Connect call failed ('192.168.178.51', 6053) (SocketAPIError)
INFO Trying to connect to luxtronik-v1-esp32.local in the background

I don't know, if there is a way to provide e.g. logs over serial connection.
To get the esp back to work, I have to connect it via USB to my computer and flash it via COM connection + force it to boot mode.

**Comment by CBrosius** [comment]
Still not able to reproduce this. My ESP32 is always connected to the heatpump as yours. Updated flawless from 2023.10.0 to 2023.10.1 to 2023.10.2 to 2023.10.3 to 2023.10.5.

**Comment by optimismus** [comment]
May be it has to do with my flashed version. I flashed the ESPs from cmd-ESPHOME on Windows 11. I will try to flash an ESP from HA.

**Comment by buzz1976** [comment]
I have the same issue 

INFO ESPHome 2023.10.5
INFO Reading configuration /config/esphome/luxtronik-v1-esp32.yaml...
INFO Starting log output from luxtronik-v1-esp32.local using esphome API
WARNING Can't connect to ESPHome API for luxtronik-v1-esp32.local: Error connecting to ('192.168.178.140', 6053): [Errno 111] Connect call failed ('192.168.178.140', 6053) (SocketAPIError)
INFO Trying to connect to luxtronik-v1-esp32.local in the background

**Comment by buzz1976** [comment]
Hello,
i found the error! There is a double line in the yaml-file.
Please delete one line and it works

 - name: "WP_Status_Betriebszustand"
 - name: "WP_Status_Betriebszustand"

Regards Thorsten

**Comment by CBrosius** [comment]
Hi Thorsten, good finding. In my local code the duplicate line is not there, but in the repo it was. (I already commited the fix)
@optimismus Does that fix your issue, too?

**Comment by buzz1976** [comment]
Hello,
after the web server on the ESP32 is now running, I have another issue with receiving data from the heat pump. The state for all values shows only "NA." I have checked the heat pump with Putty and it's working. The command 1100 is also being sent via the ESP32 and receives data. However, these data are not processed by the parser. Is there anything known that could be causing this issue?
Regards Thorsten

**Comment by CBrosius** [comment]
> The command 1100 is also being sent via the ESP32 and receives data.

How did you check that it receives data? Did you see the response in the ESP-Log?
Most of the time the data gets not processed, it is because of cabling-issues.

**Comment by optimismus** [comment]
My ESP ist working with 2023.10.6 now.

**Comment by optimismus** [comment]
My ESP is working with Firmware: 2023.10.6.
off topic: May be activate "discussion" in github for this repro.
